# Generated by Django 2.2 on 2023-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_auto_20230611_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_gan',
            name='image',
            field=models.ImageField(upload_to='ESRGAN/LR/'),
        ),
    ]
