"""
Django settings for OCRdJANGO_BETA_PROJECT project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from .info import *

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
'''
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT
'''

MEDIA_DIR = os.path.join(BASE_DIR, 'media')

MEDIA_DIR_GAN = os.path.join(BASE_DIR, 'ESRGAN')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3iy1_92_hl-z#r5d^6txp%ygcp4l+)qb1=%t0hucubktd&-ete'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['django-env.eba-4pqcvaud.us-west-2.elasticbeanstalk.com',"*"]

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ocrapp.apps.OcrappConfig',
    'crispy_forms',
    'bootstrap_modal_forms',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'OCRdJANGO_BETA_PROJECT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'OCRdJANGO_BETA_PROJECT.wsgi.application'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '/cloudsql/temp-aevolveai-project-uat1:us-east1:mysql-uat1',
        'USER': 'root',
        'PASSWORD': '12345',
        'NAME': '_aevolvedbuat1',
        'PORT': '3306'
    }
}

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

'''
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '/cloudsql/temp-aevolveai-project-uat1:us-east1:mysql-uat1',
        'USER': 'root',
        'PASSWORD': '12345',
        'NAME': '_aevolvedbuat1',
        'PORT': '3306'
    }
}

'''
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        # 'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'ocr-db',
        # 'USER': 'root',
        # 'PASSWORD': '12345',
        # 'HOST': '%',
        # 'PORT': '3306'

    },
}
'''
DATABASES = {

        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aevolve_uat',
        'USER': 'root',
        'PASSWORD': 'Marl_boro0',
        'HOST': '127.0.0.1',
        'PORT': '3306'

    },
}

'''
try:
    import MySQLdb  # noqa: F401
except ImportError:
    import pymysql

    pymysql.install_as_MySQLdb()

# [START db_setup]
if os.getenv('GAE_APPLICATION', None):
    print('Connecting to Cloud SQL for MySQL instance ...')
    # Running on production App Engine, so connect to Google Cloud SQL using
    # the unix socket at /cloudsql/<your-cloudsql-connection string>
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/temp-aevolveai-project-uat1:us-east1:mysql-uat1',
            'USER': 'root',
            'PASSWORD': '12345',
            'NAME': '_aevolvedbuat1'
        }
    }


else:
    print('Connecting to local MySQL/or through proxy ...')
    # Running locally so connect to either a local MySQL instance or connect
    # to Cloud SQL via the proxy.  To start the proxy via command line:
    #    $ cloud_sql_proxy -instances=[INSTANCE_CONNECTION_NAME]=tcp:3306
    # See https://cloud.google.com/sql/docs/mysql-connect-proxy
    DATABASES = {
        # 'default': {
        #    'ENGINE': 'django.db.backends.mysql',
        #    'HOST': '127.0.0.1',
        #    'PORT': '3306',
        #    'NAME': '[YOUR-DATABASE]',
        #    'USER': '[YOUR-USERNAME]',
        #    'PASSWORD': '[YOUR-PASSWORD]',
        # }

        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'ocr_uat_new',
            'USER': 'dbadmin',
            'PASSWORD': '12345',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }

# [END db_setup]

'''

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/staticfiles/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'staticfiles'),
    os.path.join(BASE_DIR, 'staticfiles\register_staticfiles'),
)

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'

MEDIA_GAN_ROOT = MEDIA_DIR_GAN
MEDIA_GAN_URL = '/ESRGAN/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATIC_ROOT = "/var/www/example.com/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Email settings

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_HOST_USER = 'darknessinside87@hotmail.com'
EMAIL_HOST_PASSWORD = 'Marl_boro0'
EMAIL_PORT = '587'
# DEFAULT_FROM_EMAIL = 'djangotestemailsangram@gmail.com'
# EMAIL_USE_SSL = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
